# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.


$script = <<SCRIPT
    wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
    #sudo add-apt-repository ppa:vbernat/haproxy-1.7
    sudo apt-get update 
    sudo apt-get -y --allow-unauthenticated install haproxy
    sudo apt-get install salt-minion -y
    #sudo apt-get upgrade salt-minion -y

SCRIPT

Vagrant.configure("2") do |config|
# The most common configuration options are documented and commented below.
# For a complete reference, please see the online documentation at
# https://docs.vagrantup.com.

# Every Vagrant development environment requires a box. You can search for
# boxes at https://vagrantcloud.com/search.

config.vm.define "proxy" do |proxy|
    proxy.vm.box = "envimation/ubuntu-xenial"
    proxy.vm.box_version = "1.0.3-1505610905"
    proxy.vm.provision "shell", inline: $script
    proxy.vm.synced_folder "files/", "/etc/apt/sources.list.d"
    proxy.ssh.insert_key = false
    
  end
 
  
end